spring:
  application:
    name: "MagicItems"
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5433/magic-items
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    database-platform: ${DB_DIALECT}
    properties:
      hibernate:
        dialect: ${DB_DIALECT}
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: create-drop
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION}

user:
  password:
    bcrypt: ${USER_PASSWORD_BCRYPT}
