name: workflow.yml
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-scan:
    name: Build and Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: | 
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{runner.os}}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build --stacktrace

      - name: Run SpotBugs
        run: ./gradlew spotbugsMain spotbugsTest

      - name: Upload SpotBugs XML report
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: reports/spotbugs.xml
          overwrite: true
      - name: Upload SpotBugs HTML report
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: reports/spotbugs.html
          overwrite: true
      - name: Run OWASP Dependency-Check
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          if [ -z "$NVD_API_KEY" ]; then
            echo "NVD_API_KEY is empty"
            exit 1
          else
            echo "NVD_API_KEY is set, length: $(echo -n "$NVD_API_KEY" | wc -c)"
          fi

      - name: Upload Dependency-Check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/dependency-check-report.html
          overwrite: true
